
project_name: Ansible_Demo
template_name: wlc_9300_config

filter: device_family
filter_value: Cisco Catalyst 9300 Switch

cli_template: |
  !
  clock timezone shanghai 8
  service timestamps log datetime localtime show-timezone

