
project_name: Ansible_Demo_0818
template_name: demo_9800_0818

filter: device_family
filter_value: Cisco Catalyst 9800-CL Wireless Controller for Cloud

cli_template: |
  !
  clock timezone BeiJing 8
  service timestamps log datetime localtime show-timezone

