
project_name: Ansible_Demo
template_name: wlc_9800_config

filter: device_family
filter_value: Cisco Catalyst 9800-CL Wireless Controller for Cloud

cli_template: |
  !
  service timestamps debug datetime localtime
  service timestamps log datetime localtime
  
