
project_name: Ansible_Demo
template_name: demo_9800_config

filter: device_family
filter_value: Cisco Catalyst 9800-CL Wireless Controller for Cloud

cli_template: |
  !
  clock timezone shanghai 8
  service timestamps log datetime localtime show-timezone

